name: CI
on:
  pull_request:
    branches: [develop]
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pulling the code
        uses: actions/checkout@v3
      - run: npm install
      - run: npm run format:check
      - run: npm run test -- --coverage
        env:
          CI: true
      - name: Build the project
        if: github.event == "push"
        run: npm run build
      - name: Deploy the project in the staging server
        if: github.event == "push"
        run: surge --domain foolish-bikes.surge.sh --project ./build
        env:
          SURGE_LOGIN: ${{secrets.SURGE_LOGIN}}
          SURGE_TOKEN: ${{secrets.SURGE_TOKEN}}
